// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Banner.tsx";
import * as $$$$$$1 from "./sections/BigNumbers.tsx";
import * as $$$$$$2 from "./sections/Blog.tsx";
import * as $$$$$$3 from "./sections/BlogPost.tsx";
import * as $$$$$$4 from "./sections/ColumnSection.tsx";
import * as $$$$$$5 from "./sections/Contact.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$7 from "./sections/FundraisingToolkitSection.tsx";
import * as $$$$$$8 from "./sections/Gallery.tsx";
import * as $$$$$$9 from "./sections/Head.tsx";
import * as $$$$$$10 from "./sections/Header.tsx";
import * as $$$$$$11 from "./sections/HeroCompany.tsx";
import * as $$$$$$12 from "./sections/IframeSection.tsx";
import * as $$$$$$13 from "./sections/Image.tsx";
import * as $$$$$$14 from "./sections/Manifest.tsx";
import * as $$$$$$15 from "./sections/Newsletter.tsx";
import * as $$$$$$16 from "./sections/OpinionSection.tsx";
import * as $$$$$$17 from "./sections/OrangeColumnSection.tsx";
import * as $$$$$$18 from "./sections/PartnersFooter.tsx";
import * as $$$$$$19 from "./sections/ReportSection.tsx";
import * as $$$$$$20 from "./sections/Showcase.tsx";
import * as $$$$$$21 from "./sections/Testimony.tsx";
import * as $$$$$$22 from "./sections/Theme/Theme.tsx";
import * as $$$$$$23 from "./sections/TitleSection.tsx";
import * as $$$$$$24 from "./sections/ToolkitSection.tsx";

const manifest = {
  "sections": {
    "site/sections/Banner.tsx": $$$$$$0,
    "site/sections/BigNumbers.tsx": $$$$$$1,
    "site/sections/Blog.tsx": $$$$$$2,
    "site/sections/BlogPost.tsx": $$$$$$3,
    "site/sections/ColumnSection.tsx": $$$$$$4,
    "site/sections/Contact.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/FundraisingToolkitSection.tsx": $$$$$$7,
    "site/sections/Gallery.tsx": $$$$$$8,
    "site/sections/Head.tsx": $$$$$$9,
    "site/sections/Header.tsx": $$$$$$10,
    "site/sections/HeroCompany.tsx": $$$$$$11,
    "site/sections/IframeSection.tsx": $$$$$$12,
    "site/sections/Image.tsx": $$$$$$13,
    "site/sections/Manifest.tsx": $$$$$$14,
    "site/sections/Newsletter.tsx": $$$$$$15,
    "site/sections/OpinionSection.tsx": $$$$$$16,
    "site/sections/OrangeColumnSection.tsx": $$$$$$17,
    "site/sections/PartnersFooter.tsx": $$$$$$18,
    "site/sections/ReportSection.tsx": $$$$$$19,
    "site/sections/Showcase.tsx": $$$$$$20,
    "site/sections/Testimony.tsx": $$$$$$21,
    "site/sections/Theme/Theme.tsx": $$$$$$22,
    "site/sections/TitleSection.tsx": $$$$$$23,
    "site/sections/ToolkitSection.tsx": $$$$$$24,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
